import Head from 'next/head'
import Hero from '@/components/Hero'
import { Navbar } from '@/components/Navbar'
import Features from '@/components/Features'
import Footer from '@/components/Footer'
import NewsLetter from '@/components/NewsLetter'
import ProductNews from '@/components/ProductNews'
import Clients from '@/components/Clients'
import AppSection from '@/components/App'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='flex flex-col w-[1000px] items-center mx-auto pb-20'>
        <Hero />
        <Features />
        <AppSection />
        <ProductNews />
        <Clients />
        <NewsLetter />
      </div>
      <Footer />
    </>
  )
}
